import { defineConfig, devices } from '@playwright/test';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CI = Boolean(process.env.CI);
const BASE_URL = 'http://localhost:5173';
const rootDir = dirname(fileURLToPath(import.meta.url));
/** Generated by `npm run generate:tones` (run automatically by `npm run test:e2e`). */
const fakeAudioFile = join(rootDir, 'e2e', 'fixtures', 'tone-a4-440hz.wav');

export default defineConfig({
  testDir: 'e2e',
  timeout: 30_000,
  expect: { timeout: 10_000 },
  retries: CI ? 2 : 0,
  workers: 1,
  reporter: CI ? [['list'], ['html', { open: 'never' }]] : 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: {
          args: [
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream',
            `--use-file-for-fake-audio-capture=${fakeAudioFile}`,
            '--autoplay-policy=no-user-gesture-required',
          ],
        },
      },
    },
  ],
  webServer: {
    command: 'npm run dev:e2e',
    url: BASE_URL,
    reuseExistingServer: !CI,
    timeout: 60_000,
  },
});
